############################
## CHANGE THESE
############################

baseURL: "https://www.provenaisolutions.com/blog"
title: proven-blog
canonifyURLs: false

module:
  imports:
    - path: github.com/chrede88/qubt/v2

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true

