############################
## CHANGE THESE
############################

baseURL: "https://dataGladiator.github.io/proven-blog"
title: proven-blog

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
