############################
## Navbar
############################

main:
- name: Home
  url: "https://www.provenaisolutions.com"
  weight: 10
- name: Blog
  url: "https://www.provenaisolutions.com/blog/blog"
  weight: 20
- name: Contact
  url: "https://www.provenaisolutions.com/#contact"
  weight: 30

